/**
 * Integration tests verifying that SWC can actually compile .tsx files
 * using the config generated by getSwcRcConfig().
 *
 * These use @swc/core's transformSync directly — no filesystem, no NestJS CLI.
 * We're testing the real SWC compiler against real .tsx code patterns
 * that appear in nestjs-ssr projects.
 */
import { describe, it, expect } from 'vitest';
import { transformSync, type Options } from '@swc/core';
import { getSwcRcConfig } from '../swc-support';

/**
 * Builds the full SWC options by merging NestJS CLI defaults with our .swcrc.
 * This mirrors what NestJS's SwcCompiler.deepMerge() does at runtime.
 */
function buildSwcOptions(): Options {
  // NestJS CLI hardcoded defaults (from @nestjs/cli/lib/compiler/defaults/swc-defaults.js)
  const nestDefaults: Options = {
    module: { type: 'commonjs' },
    jsc: {
      target: 'es2021',
      parser: {
        syntax: 'typescript',
        decorators: true,
        dynamicImport: true,
      },
      transform: {
        legacyDecorator: true,
        decoratorMetadata: true,
        useDefineForClassFields: false,
      },
      keepClassNames: true,
    },
    minify: false,
  };

  const swcrc = getSwcRcConfig() as Options;

  // Simulate NestJS's deep merge: swcrc overrides/extends nestDefaults
  const merged: Options = {
    ...nestDefaults,
    jsc: {
      ...nestDefaults.jsc,
      ...swcrc.jsc,
      parser: {
        ...((nestDefaults.jsc?.parser ?? {}) as object),
        ...((swcrc.jsc?.parser ?? {}) as object),
      } as Options['jsc'] extends { parser?: infer P } ? P : never,
      transform: {
        ...((nestDefaults.jsc?.transform ?? {}) as object),
        ...((swcrc.jsc?.transform ?? {}) as object),
      } as Options['jsc'] extends { transform?: infer T } ? T : never,
    },
  };
  return merged;
}

describe('SWC .tsx compilation', () => {
  const options = buildSwcOptions();

  it('compiles a basic React component', () => {
    const code = `
      import React from 'react';

      export default function HomePage({ title }: { title: string }) {
        return <h1>{title}</h1>;
      }
    `;

    const result = transformSync(code, {
      ...options,
      filename: 'home.tsx',
    });

    expect(result.code).toBeDefined();
    expect(result.code).toContain('jsx-runtime');
    expect(result.code).toContain('HomePage');
    expect(result.code).not.toContain('<h1>');
  });

  it('compiles a component with NestJS decorators imported alongside JSX', () => {
    // This is the actual pattern: a controller file that imports .tsx components
    const code = `
      import { Controller, Get } from '@nestjs/common';
      import { Render } from '@nestjs-ssr/react';
      import Home from './views/home';

      @Controller()
      export class AppController {
        @Get()
        @Render(Home)
        getHome() {
          return { title: 'Hello' };
        }
      }
    `;

    const result = transformSync(code, {
      ...options,
      filename: 'app.controller.ts',
    });

    expect(result.code).toBeDefined();
    expect(result.code).toContain('AppController');
    expect(result.code).toContain('./views/home');
  });

  it('compiles JSX with fragments', () => {
    const code = `
      export default function List({ items }: { items: string[] }) {
        return (
          <>
            {items.map((item, i) => (
              <li key={i}>{item}</li>
            ))}
          </>
        );
      }
    `;

    const result = transformSync(code, {
      ...options,
      filename: 'list.tsx',
    });

    expect(result.code).toBeDefined();
    expect(result.code).toContain('jsx-runtime');
    expect(result.code).not.toContain('<li');
    expect(result.code).not.toContain('<>');
  });

  it('compiles a layout component with children prop', () => {
    const code = `
      import React from 'react';

      interface LayoutProps {
        children: React.ReactNode;
      }

      export default function RootLayout({ children }: LayoutProps) {
        return (
          <html lang="en">
            <body>
              <nav>Navigation</nav>
              <main>{children}</main>
            </body>
          </html>
        );
      }
    `;

    const result = transformSync(code, {
      ...options,
      filename: 'layout.tsx',
    });

    expect(result.code).toBeDefined();
    expect(result.code).toContain('RootLayout');
    expect(result.code).toContain('jsx-runtime');
    expect(result.code).not.toContain('<html');
  });

  it('compiles component using client-side hooks from the library', () => {
    const code = `
      import { createSSRHooks } from '@nestjs-ssr/react/client';

      const { usePageContext, useParams } = createSSRHooks();

      export default function ProductPage({ data }: { data: { name: string } }) {
        const { path } = usePageContext();
        const { id } = useParams<{ id: string }>();
        return (
          <div>
            <h1>{data.name}</h1>
            <p>Path: {path}, ID: {id}</p>
          </div>
        );
      }
    `;

    const result = transformSync(code, {
      ...options,
      filename: 'product.tsx',
    });

    expect(result.code).toBeDefined();
    expect(result.code).toContain('ProductPage');
    expect(result.code).toContain('usePageContext');
    expect(result.code).toContain('jsx-runtime');
  });

  it('uses automatic runtime (no React import needed for JSX)', () => {
    // With "runtime": "automatic", JSX should compile without explicit React import
    const code = `
      export default function Minimal() {
        return <div>works</div>;
      }
    `;

    const result = transformSync(code, {
      ...options,
      filename: 'minimal.tsx',
    });

    expect(result.code).toBeDefined();
    expect(result.code).toContain('jsx-runtime');
    // Should NOT require a manual React import
    expect(result.code).not.toMatch(/require\(["']react["']\)/);
  });
});
