#!/usr/bin/env node
import { glob } from 'glob';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const REGISTRY_FILE = path.resolve(
  __dirname,
  '../src/view/view-registry.generated.ts',
);
const SRC_DIR = path.resolve(__dirname, '../src');

async function generateRegistry() {
  try {
    // Find all view files in src/**/views/*.tsx
    // Exclude shared/views/* (those are components, not page views)
    const viewFiles = await glob('**/views/*.tsx', {
      cwd: SRC_DIR,
      absolute: false,
      ignore: ['shared/views/**'],
    });

    if (viewFiles.length === 0) {
      console.warn('[generate-view-registry] No view files found');
      return;
    }

    // Generate imports and registry entries
    const imports: string[] = [];
    const registryEntries: string[] = [];

    viewFiles.forEach((file) => {
      // Convert file path to component name
      // Replace hyphens with underscores first, then convert to PascalCase
      const componentName = file
        .replace(/\.tsx$/, '')
        .replace(/-/g, '_') // Convert hyphens to underscores
        .replace(/\//g, '_')
        .split('_')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join('');

      // Create import path relative to src/view/
      const importPath = `../${file.replace(/\.tsx$/, '')}`;

      // Create registry key
      const registryKey = file.replace(/\.tsx$/, '');

      imports.push(`import ${componentName} from '${importPath}';`);
      registryEntries.push(`  '${registryKey}': ${componentName},`);
    });

    // Generate the TypeScript file
    const registryContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * This file is automatically generated by the view-registry-plugin.
 * Any manual changes will be overwritten.
 *
 * To add a new view, simply create a .tsx file in any module's views/ directory.
 * The view will be automatically registered and available for use.
 */

import React from 'react';

${imports.join('\n')}

/**
 * View registry mapping paths to React components.
 * This is auto-generated from all files matching the pattern.
 */
export const viewRegistry: Record<string, React.ComponentType<any>> = {
${registryEntries.join('\n')}
};

/**
 * Get all registered view paths.
 */
export function getRegisteredViews(): string[] {
  return Object.keys(viewRegistry);
}

/**
 * Check if a view path is registered.
 */
export function isViewRegistered(path: string): boolean {
  return path in viewRegistry;
}
`;

    // Write the generated file
    fs.writeFileSync(REGISTRY_FILE, registryContent, 'utf-8');

    const count = viewFiles.length;
    console.log(
      `✅ Generated view registry with ${count} view${count === 1 ? '' : 's'}`,
    );
  } catch (error) {
    console.error('❌ Failed to generate view registry:', error);
    process.exit(1);
  }
}

generateRegistry();
