/**
 * Helpers for fixtures generated by `nest new`.
 *
 * Nest 12's CLI scaffolds ES module projects ("type": "module", `nodenext`
 * resolution), where a relative import must name the emitted file:
 * `./views/counter.js`, not `./views/counter`. Nest 11 scaffolds CommonJS,
 * where the extensionless form is idiomatic. The fixture templates are
 * written once, extensionless, and adapted here, which is exactly the edit a
 * Nest 12 user makes by hand.
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'fs';
import { join } from 'path';

/** Whether the scaffolded project is an ES module package. */
export function isEsmProject(projectDir: string): boolean {
  const pkg = JSON.parse(
    readFileSync(join(projectDir, 'package.json'), 'utf-8'),
  ) as { type?: string };
  return pkg.type === 'module';
}

const RELATIVE_SPECIFIER =
  /(\bfrom\s+|\bimport\s*\(\s*|\bimport\s+)(['"])(\.{1,2}\/[^'"]+?)\2/g;

/** Append `.js` to extensionless relative specifiers in one source text. */
export function addJsExtensions(source: string): string {
  return source.replace(
    RELATIVE_SPECIFIER,
    (match, prefix: string, quote: string, specifier: string) =>
      /\.(?:[cm]?js|json|css)$/.test(specifier)
        ? match
        : `${prefix}${quote}${specifier}.js${quote}`,
  );
}

/**
 * Rewrite every `.ts`/`.tsx` file under `srcDir` for ESM resolution.
 * Vite entry files are skipped: Vite resolves them itself, and they import
 * through the `@/` alias and `import.meta.glob`, not relative paths.
 */
export function adaptSourcesForEsm(srcDir: string): number {
  let changed = 0;
  for (const entry of readdirSync(srcDir)) {
    const path = join(srcDir, entry);
    if (statSync(path).isDirectory()) {
      changed += adaptSourcesForEsm(path);
      continue;
    }
    if (!/\.tsx?$/.test(entry) || /^entry-(client|server)\.tsx$/.test(entry)) {
      continue;
    }
    const before = readFileSync(path, 'utf-8');
    const after = addJsExtensions(before);
    if (after !== before) {
      writeFileSync(path, after);
      changed++;
    }
  }
  return changed;
}
