import { defineConfig } from 'tsdown';

/**
 * Output is kept byte-for-byte compatible in *shape* with the previous tsup
 * build: the same entry paths, `.mjs` + `.d.mts` for ESM and `.js` + `.d.ts`
 * for CommonJS, because the export map and every consumer's resolution depend
 * on those names.
 *
 * Declarations are generated by TypeScript 7's native compiler (tsdown picks
 * the `tsgo` generator when TypeScript 7 is installed as `typescript`).
 */
export default defineConfig({
  entry: {
    index: 'src/index.ts',
    client: 'src/client.ts',
    'render/index': 'src/render/index.ts',
    'cli/init': 'src/cli/init.ts',
  },
  format: ['esm', 'cjs'],
  platform: 'node',
  // Gives the ESM build `__dirname`/`__filename` (and the CJS build
  // `import.meta.url`). Nest 12 applications are ES modules and load the
  // `.mjs` build, where a bare `__dirname` is a ReferenceError.
  shims: true,
  target: 'es2022',
  outExtensions: ({ format }) =>
    format === 'es'
      ? { js: '.mjs', dts: '.d.mts' }
      : { js: '.js', dts: '.d.ts' },
  // declarationMap is on in tsconfig for editor navigation inside the repo;
  // the published package ships no maps, as before.
  dts: { sourcemap: false },
  sourcemap: false, // Keeps the package small (~870KB saved)
  clean: true,
  treeshake: true,
  minify: false,
  // JSDoc stays in the .d.ts files, where editors read it; the runtime JS
  // drops it (esbuild did the same under tsup). Annotations are kept:
  // `@__PURE__` lets consumers tree-shake, `@vite-ignore` silences Vite on
  // the intentional dynamic imports.
  outputOptions: {
    comments: { legal: true, annotation: true, jsdoc: false },
  },
  deps: {
    // Each name also matches its subpaths (`rxjs/operators`, `react-dom/server`,
    // `@nestjs/common/...`). tsup's `external` matched by prefix; tsdown matches
    // exact names, and an unmatched `rxjs/operators` import pulled a private
    // copy of rxjs into the bundle, which breaks Observable identity checks
    // against the application's rxjs.
    neverBundle: [
      '@nestjs/common',
      '@nestjs/core',
      '@nestjs/platform-express',
      'express',
      'react',
      'react-dom',
      'vite',
      'rxjs',
    ].map((name) => new RegExp(`^${name.replace('/', '\\/')}(?:/|$)`)),
  },
  copy: [{ from: 'src/templates', to: 'dist' }],
});
